version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-lab
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "${VAULT_TOKEN}"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - lab-net

  # Container auxiliar que lê do .env e popula o Vault automaticamente
  vault-init:
    image: hashicorp/vault:latest
    container_name: vault-init-setup
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "${VAULT_TOKEN}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - vault
    command: >
      sh -c "
        echo 'Aguardando o Vault iniciar...'
        sleep 3
        echo 'Gravando segredos no Vault...'
        vault kv put secret/db user='$DB_USER' password='$DB_PASSWORD'
        echo 'Segredos gravados com sucesso!'
      "
    networks:
      - lab-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_local_lab
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - lab-net

  api:
    build: .
    container_name: api_python_lab
    ports:
      - "8080:80"
    environment:
      - DB_SERVER=db
      - DB_NAME=appdb
      - VAULT_URL=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    depends_on:
      - vault
      - vault-init
      - db
    networks:
      - lab-net

networks:
  lab-net:
    driver: bridge
